### ISSUE TITLE
problem when downloading latest veloren build

### ISSUE THREAD

**Issue by Herbert-Karl** [Songtronix/Airshipper#100]
when trying to use the current release and self build of airshipper, the download cancels at 24% with following error message:
![grafik](https://user-images.githubusercontent.com/34774005/99886221-1d3a8880-2c3b-11eb-98a7-d5fa66e3ff39.png)

Plattform: Windows 10
Toolchain: nightly-2020-06-10-x86_64-pc-windows-msvc

**Comment by Songtronix** [comment]
Based on the investigations we did the issue seems to be the [CDN](https://www.digitalocean.com/products/spaces/) not properly distributing. However I'm currently still investigating the exact cause as it might be an error with the airshipper server.

**Comment by Songtronix** [comment]
Has been fixed by just not relying on the CDN.
