### ISSUE TITLE
(v0.4.1) Error self-updating Airshipper on Windows 10: msiexec help is displayed instead of executing update

### ISSUE THREAD

**Issue by cworobetz** [Songtronix/Airshipper#116]
Hello,

When trying to update Airshipper to the latest version via Airshipper v0.4.1, I receive the msiexec help instead of having the msi execute. In my experience as a sysadmin, this happens when you use the incorrect arguments.

The msiexec command it's trying to execute takes the following form:

`"C:\Windows\System32\msiexec.exe" /passive /i C:\Users\Example User\AppData\Local\airshipper\airshipper-windows.msi /L*V C:\Users\Example User\AppData\Local\airshipper\airshipper-install.log AUTOSTART=1`

It seems the issue is that since I have a space in my username, it's interpreting the `C:\` paths as two seperate arguments instead of one. This could be resolved by quoting those arguments. I have attached a link to the relevant code below. Thx

https://github.com/Songtronix/Airshipper/blob/ff875aa4aa41540fe4c34f66ad62b349ca278bdb/client/src/windows.rs#L95

**Comment by Songtronix** [comment]
Fixed (cherry-picked) in #159 and to be included in the 0.4.3 release which will come soon.
