### ISSUE TITLE
BSD Version

### ISSUE THREAD

**Issue by ALipAkrohk** [Songtronix/Airshipper#117]
Why no version available for BSD Os ?!
I'm using freeBSD OS How do I install AirShiper Launcher?

**Comment by Songtronix** [comment]
Do I look like I know every operating system out there? 😄 I don't know anything about BSD nor whether Veloren even runs on it so if someone gets it working it I'm sure accepting an MR. But based on the wikipedia article you might just be able to run the linux version of airshipper. So download it ( https://veloren.net/download/ ), `chmod +x airshipper` to make it executable and then run it.

**Comment by ALipAkrohk** [comment]
Veloren is available on FreeBSD with its package managers(both pkg and ports directories). Should i need to compile Airshipper with rustc(its package available too)?

**Comment by Songtronix** [comment]
Closing in favour of #120
