### ISSUE TITLE
Veloren Downloads As Text File - Mac

### ISSUE THREAD

**Issue by BretMishler** [Songtronix/Airshipper#119]
**Describe the bug**
All macOS sources of AirShipper download as a text file.

**To Reproduce**
1. Go to:

- https://veloren.net/download/
- https://songtronix.com

2. Download

**Expected behavior**
An automatically executable launcher.

**Screenshots**
![image](https://user-images.githubusercontent.com/8965315/109441914-87f22180-79eb-11eb-85bc-a75d22dd4732.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.1

**Additional context**

**Comment by Songtronix** [comment]
I don't have a mac myself so the experience might not be that good :/ However you can fix it easily by opening a terminal containing the Airshipper executable and running:
```
chmod +x ./airshipper
./airshipper
```

Will need to check how macos deals with these kind of things so it detects it as an executable by itself.

**Comment by BretMishler** [comment]
Hey there. Thanks for the response - I know how to turn files into executables but I wanted to report this problem anyways. As a fellow developer, I would suggest not closing this ticket at the problem isn't actually solved and you're losing an entire audience of non-technical individuals who aren't aware of how to chmod a file. 

Try something like this:

https://webmasters.stackexchange.com/a/15598

**Comment by Songtronix** [comment]
Your suggested hack cannot be applied here as github hosts the binaries and as such I cannot modify github's behaviour.

Opened #120 to address the grand problem that airshipper currently is not well integrated into the users varying systems.
