### ISSUE TITLE
Airshipper app does not open on Mac

### ISSUE THREAD

**Issue by ArnoldGee** [Songtronix/Airshipper#127]
**Describe the bug**
I want to download and install the Airshipper app for mac, but I am unable to open the installer correctly.

**To Reproduce**
1. Go to https://www.veloren.net/download/ and download the .zip file
2. Unzip the file
3. Double click on the icon of the program
4. Instead of opening the program, it opens like a text file

**Expected behavior**
Airshipper program should open like a .dmg or a normal Mac program, not like a text file

**Screenshots**
The file looks like this:
![Captura de pantalla 2021-03-28 a las 21 00 56](https://user-images.githubusercontent.com/66358043/112764420-ba059c00-9008-11eb-8861-9fa8ef57193c.png)
And the program opens like this: 
![imagen](https://user-images.githubusercontent.com/66358043/112764454-de617880-9008-11eb-9581-858c5235ce21.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - GPU: Intel

**Additional context**
I don't know Rust.

**Comment by Songtronix** [comment]
see #120 for details. You need to mark airshipper as executable beforehand.

**Comment by ArnoldGee** [comment]
Thanks Songtronix. I don't know how to mark a program as executable, I guess it's by running the `chmod -x airshipper` command?
I did this but nothing has changed, the program is behaving the same way when I double-click on it.

**Comment by ArnoldGee** [comment]
This is what I did to solve the issue. It would be helpful to include it in the documentation for other newbies like me.
1. Go to the folder where the `airshipper` file is located and open the Terminal there.
2. Execute the following command:
```bash
chmod a+rwx airshipper
```
Go back to Finder and double-click on the icon of the program.

**Comment by Songtronix** [comment]
> Thanks Songtronix. I don't know how to mark a program as executable, I guess it's by running the `chmod -x airshipper` command?
> I did this but nothing has changed, the program is behaving the same way when I double-click on it.

because it's `chmod +x`. `a+rwx` is not needed. Devils details I know. I close this in favor of #120 as ideally I want to ship an installer of some sort which makes all the terminal hassle redundant.
