### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by f1nniboy** [Songtronix/Airshipper#128]
**Is your feature request related to a problem? Please describe.**
Using the CLI can be frustrating. When having an update and not launching from the terminal, you won't be able to update unless you execute Airshipper in the terminal.

**Describe the solution you'd like**
Add support for Wayland.

**Describe alternatives you've considered**
Keep using the CLI.

**Additional context**
Opening Airshipper when using Wayland, it prints this message and only allows me to use the CLI:
`[ERROR] IcedError => a suitable graphics adapter or device could not be found`

**Comment by Songtronix** [comment]
Wayland support already exists, although still a bit wonky. You can force x11 by setting the `WINIT_UNIX_BACKEND` environment variable to `x11`. This error also does not hint on missing wayland support. More likely gpu related or package missing like `vulkan-icd-loader`.

Furthermore I sadly just consume the libraries and can't do anything else than regularly update them :/
