### ISSUE TITLE
Airshipper GUI doesn't scale well on small laptop screen

### ISSUE THREAD

**Issue by zayuim** [Songtronix/Airshipper#131]
**Describe the bug**
Airshipper window has a minimum height which doesn't scale well on smaller laptop screens. Mine is 1600x900, which results in the bottom of the window being cut-off by the KDE Plasma taskbar.

**Screenshots**
![Screenshot_20210404_154135](https://user-images.githubusercontent.com/22744080/113499874-e36c7d80-955c-11eb-8198-4a7dbb09c0fc.png)
Window is maximized.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux (latest). KDE Plasma.
 - GPU NVIDIA GF108M

**Comment by Songtronix** [comment]
[1050x620](https://github.com/Songtronix/Airshipper/blob/master/client/src/gui/mod.rs#L259) is currently the minimum size but it's entirely configurable. If you're able to compile yourself I would be glad to know a sane value which works with your setup!

**Comment by Songtronix** [comment]
Fixed (cherry-picked) in #159 and to be included in the 0.4.3 release which will come soon. Feel free to reopen if 0.4.3 does not fix it.
