### ISSUE TITLE
store db in a seperate folder than the file

### ISSUE THREAD

**Issue by xMAC94x** [Songtronix/Airshipper#149]
**Is your feature request related to a problem? Please describe.**
Many Docker systems are either having problems or weird around file mounting.
Currently we mount /opt/app/airshipper.db directly.
Docker-Compose will create a dir by default and kubernetes cant mount single files easily.

**Describe the solution you'd like**
put the airshipper.db file in a subfolder
/opt/app/data/airshipper.db
or any other subfolder.
This makes it easier to mount. And it also allows a .wal file to be used and created.

**Describe alternatives you've considered**
none - its either file or directory

**Additional context**
none

**Comment by Songtronix** [comment]
Fixed (cherry-picked) in #159 and to be included in the 0.4.3 release which will come soon.
