### ISSUE TITLE
How to run in MacOS?

### ISSUE THREAD

**Issue by linonetwo** [Songtronix/Airshipper#68]
<img width="418" alt="Screen Shot 2020-07-08 at 10 07 33 PM" src="https://user-images.githubusercontent.com/3746270/86928660-6d6eed80-c167-11ea-85a7-1c3d4cc1a52c.png">
<img width="659" alt="Screen Shot 2020-07-08 at 10 08 03 PM" src="https://user-images.githubusercontent.com/3746270/86928705-7f509080-c167-11ea-9c6c-6f647e125cea.png">

**Comment by Songtronix** [comment]
Open terminal and navigate to the file. Type `sudo chmod +x airshipper` and then start with `./airshipper`

**Comment by linonetwo** [comment]
Oh, since there are assets, I thought this can be an mac .app file
