### ISSUE TITLE
Some env vars no longer need to be set

### ISSUE THREAD

**Issue by Imberflur** [Songtronix/Airshipper#98]
`VOXYGEN_CONFIG`
and
`VOXYGEN_LOGS`
are no longer needed as these are now sensible locations by default and setting these disrupts the new structure with everything in a folder named userdata.

`VELOREN_SAVES_DIR` is no longer read

**Comment by Songtronix** [comment]
Instead set `VELOREN_USERDATA`

**Comment by Songtronix** [comment]
Will be fixed with the release of 0.4.1
